### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by geography** [planetlabs/stratus#8]
Hi all,

when I tried to build from this cmd:
cd src
mvn clean install -Dgdal

I have this error:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Stratus Parent 1.6.1-SNAPSHOT:
[INFO]
[INFO] Stratus Parent ..................................... SUCCESS [ 1.109 s]
[INFO] stratus-commons .................................... SUCCESS [ 10.490 s]
[INFO] stratus-redis-core ................................. SUCCESS [ 11.443 s]
[INFO] stratus-redis-resource-store ....................... FAILURE [ 4.039 s]
[INFO] Stratus Redis Catalog .............................. SKIPPED
[INFO] Stratus OWS Support ................................ SKIPPED
[INFO] Stratus OWS Core Support ........................... SKIPPED
[INFO] Stratus WFS Support ................................ SKIPPED
[INFO] Stratus WMS Support ................................ SKIPPED
[INFO] Stratus WCS Support ................................ SKIPPED
[INFO] stratus-extras ..................................... SKIPPED
[INFO] ndvi-process ....................................... SKIPPED
[INFO] stratus-gwc ........................................ SKIPPED
[INFO] stratus-wps ........................................ SKIPPED
[INFO] Stratus ............................................ SKIPPED
[INFO] Stratus Integration Tests .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.698 s
[INFO] Finished at: 2020-04-17T18:44:37+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project stratus-redis-resource-store: Could not resolve dependencies for project stratus:stratus-redis-resource-store:jar:1.6.1-SNAPSHOT: Failed to collect dependencies at org.geoserver:gs-platform:jar:2.16.0: Failed to read artifact descriptor for org.geoserver:gs-platform:jar:2.16.0: Could not transfer artifact org.geoserver:gs-platform:pom:2.16.0 from/to boundless (https://repo.boundlessgeo.com/artifactory/main): repo.boundlessgeo.com: Name or service not known: Unknown host repo.boundlessgeo.com: Name or service not known -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn -rf :stratus-redis-resource-store

someone can help me?
Thanks in advance,
Ema.

**Comment by joshfix** [comment]
Hi Ema, thanks for bringing this to our attention.  Recently, the repo.boundlessgeo.com artifactory server was shut down.  Everything is running through repo.osgeo.org now.  We should have the pom fixed to reflect this change soon.

**Comment by joshfix** [comment]
The repositories in the pom file should now be fixed.  Would you mind giving it another shot and letting us know if it works now?

**Comment by geography** [comment]
Hi Josh thanks for the quick response, now the results error is:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Stratus Parent 1.6.1-SNAPSHOT:
[INFO] 
[INFO] Stratus Parent ..................................... SUCCESS [  1.084 s]
[INFO] stratus-commons .................................... SUCCESS [  9.162 s]
[INFO] stratus-redis-core ................................. SUCCESS [  8.113 s]
[INFO] stratus-redis-resource-store ....................... SUCCESS [04:03 min]
[INFO] Stratus Redis Catalog .............................. SUCCESS [10:05 min]
[INFO] Stratus OWS Support ................................ SUCCESS [  0.011 s]
[INFO] Stratus OWS Core Support ........................... SUCCESS [ 30.995 s]
[INFO] Stratus WFS Support ................................ SUCCESS [07:07 min]
[INFO] Stratus WMS Support ................................ SUCCESS [10:27 min]
[INFO] Stratus WCS Support ................................ SUCCESS [01:09 min]
[INFO] stratus-extras ..................................... SUCCESS [  0.015 s]
[INFO] ndvi-process ....................................... FAILURE [  0.846 s]
[INFO] stratus-gwc ........................................ SKIPPED
[INFO] stratus-wps ........................................ SKIPPED
[INFO] Stratus ............................................ SKIPPED
[INFO] Stratus Integration Tests .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33:46 min
[INFO] Finished at: 2020-04-17T22:48:11+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project ndvi-process: Unable to generate classpath: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information for org.apache.maven.surefire:surefire-junit4:jar:2.22.2: Failed to retrieve POM for org.apache.maven.surefire:surefire-junit4:jar:2.22.2: Could not transfer artifact org.apache.maven.surefire:surefire-junit4:pom:2.22.2 from/to central (https://repo.maven.apache.org/maven2): Connection reset
[ERROR]   org.apache.maven.surefire:surefire-junit4:jar:2.22.2
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] Path to dependency: 
[ERROR] 	1) dummy:dummy:jar:1.0
[ERROR] 
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ndvi-process

Ema.

**Comment by geography** [comment]
Hi Josh, 

now it works, I think was a temporary service repo down.

Thanks,
Ema.
